<a href="https://colab.research.google.com/github/hkbaek0316-ai/2025.DM/blob/main/5%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt


In [2]:
A = {1,2,3}
B = {2,3,4}
 # A에서 B로 가는 이항관계 R
R = {(1,2),(2,3),(3,2),(3,4)}

print("관계R:",R)

관계R: {(2, 3), (3, 2), (1, 2), (3, 4)}


In [3]:
A_list = sorted(A)
B_list = sorted(B)

relation_matrix = np.zeros((len(A_list), len(B_list)), dtype=int)

for i, a in enumerate(A_list):
  for j, b in enumerate(B_list):
    if (a, b) in R:
      relation_matrix[i, j] = 1

print("관계행렬 (rows: A, columns: B):")
print(relation_matrix)

관계행렬 (rows: A, columns: B):
[[1 0 0]
 [0 1 0]
 [1 0 1]]


In [4]:
# R: A -> B
# S: B -> C
C = {'x','y'}
S = {(2,'x'), (3,'y'), (4,'x')}

# 합성 관계 R'S
composed_relation = set()

for(a,b1) in R:
  for(b2, c) in S:
    if b1 == b2:
      composed_relation.add((a,c))

print("\n합성 관계 R ' S:", composed_relation)




합성 관계 R ' S: {(2, 'y'), (3, 'x'), (1, 'x')}
